### ISSUE TITLE
Multiple incompatibilities with Django 1.10

### ISSUE THREAD

**Issue by SalahAdDin** [infoportugal/wagtail-modeltranslation#84]
Hi guys, 

Thank you for your package!

Unfortunately, with new django version we have some big problems that don't leave us work with it.

And, seems, you aren't active in this moment, here and video package too.

So, the first problem is this:

``` bash
Traceback (most recent call last):
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/wagtail_modeltranslation/apps.py", line 11, in ready
    handle_translation_registrations()
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/wagtail_modeltranslation/models.py", line 101, in handle_translation_registrations
    autodiscover()
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/wagtail_modeltranslation/models.py", line 46, in autodiscover
    import_module(module)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/wagtail_modeltranslation/translation.py", line 9, in <module>
    class PageTR(TranslationOptions):
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/wagtail_modeltranslation/decorators.py", line 23, in wrapper
    translator.register(model_or_iterable, opts_class, **options)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/wagtail_modeltranslation/translator.py", line 445, in register
    opts = self._get_options_for_model(model, opts_class, **options)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/wagtail_modeltranslation/translator.py", line 565, in _get_options_for_model
    if model._deferred:
AttributeError: type object 'Page' has no attribute '_deferred'
```

Searching in the web i found [this](https://groups.google.com/forum/#!msg/wagtail-developers/7CRlSaoyW1Y/_sUHn3EGBAAJ): `django 1.10` deprecated `deferred` attribute for model class.

So, i solved like [`wagtail` team](https://github.com/torchbox/wagtail/commit/a65c707db3705d0d63566070cea820f6da49c596):

``` python
        if VERSION < (1, 10) and getattr(model, '_deferred', False):
            model = model._meta.proxy_for_model
```

But, we have other problem:

``` bash
Traceback (most recent call last):
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/wagtail_modeltranslation/apps.py", line 11, in ready
    handle_translation_registrations()
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/wagtail_modeltranslation/models.py", line 101, in handle_translation_registrations
    autodiscover()
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/wagtail_modeltranslation/models.py", line 46, in autodiscover
    import_module(module)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/wagtail_modeltranslation/translation.py", line 9, in <module>
    class PageTR(TranslationOptions):
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/wagtail_modeltranslation/decorators.py", line 23, in wrapper
    translator.register(model_or_iterable, opts_class, **options)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/wagtail_modeltranslation/translator.py", line 469, in register
    add_manager(model)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/wagtail_modeltranslation/translator.py", line 217, in add_manager
    for _, attname, cls in model._meta.concrete_managers + model._meta.abstract_managers:
AttributeError: 'Options' object has no attribute 'concrete_managers'
```

How can we solve this?

**Comment by SalahAdDin** [comment]
@rmartins90 

Searching in "_parent_" or "_based_" package i can see that they solved the first problem in this way:
```python
if not NEW_DEFERRED_API and model._deferred:
             model = model._meta.proxy_for_model
```

Where `NEW_DEFERRED_API` is `NEW_DEFERRED_API = NEW_MANAGER_API = NEW_ABSTRACT_API = VERSION >= (1, 10)`.

**Comment by SalahAdDin** [comment]
For the second problem they change all line 217, and 218 included which this code:
```python


    managers = (
        model._meta.local_managers if NEW_MANAGER_API else (
            getattr(
                model,
                x[1]
            ) for x in model._meta.concrete_managers + model._meta.abstract_managers
        )
    )

    for current_manager in managers:
```

Deleting this line: `current_manager = getattr(model, attname)`.

But, we have, other problem!
```bash
Traceback (most recent call last):
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/wagtail_modeltranslation/apps.py", line 11, in ready
    handle_translation_registrations()
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/wagtail_modeltranslation/models.py", line 101, in handle_translation_registrations
    autodiscover()
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/wagtail_modeltranslation/models.py", line 65, in autodiscover
    WagtailTranslator(model)
  File "/home/salahaddin/Proyectos/uzman/lib/python3.5/site-packages/wagtail_modeltranslation/patch_wagtailadmin.py", line 92, in __init__
    for related_name, formset in form.formsets.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
```

**Comment by SalahAdDin** [comment]
@rmartins90 
The third problem have a simple solution, in `python3` dictionaries use `items()` instead `iteritems()`.

And like this errors, i think that many other errors can be fixed updating `django-modeltranslation` base, as beginning, and so...

But, it seems that this repository isn't active.

**Comment by SalahAdDin** [comment]
Other incompatibilitie solved in "_parent_" package:
Line __248__ change with this: `if NEW_DEFERRED_API or not self._deferred:`.

I insist, update based "_parent_" package.

I think that i'll finishing updating it, but, you don't merge pull request @rmartins90 .

**Comment by begonaalvarezd** [comment]
Hello!

I was trying to include your package in my project under Django 1.10 and, as seen in previous releases, I get the following error:

`from wagtail.wagtailadmin.views.pages import get_page_edit_handler,\
ImportError: cannot import name get_page_edit_handler`

Any ideas how to fix it? I have already tried to install in my virtualenv both versions wagtail-modeltranslation==0.4.2 && wagtail-modeltranslation==0.4.4 with no luck. 

Thank you!!

**Comment by giammi** [comment]
Hello,

Thanks for this package as I need it for setting up a multilingual website.

Unfortunately I get the same error message as @begonaalvarezd which jeopardizes my project.

`from wagtail.wagtailadmin.views.pages import get_page_edit_handler,\
ImportError: cannot import name 'get_page_edit_handler'`

Any hints on how to solve this issue? Thanks.

**Comment by yeisonvargasf** [comment]
@begonaalvarezd, @giammi Install the fix with:

`pip3 install -e git+https://github.com/yeisonvargasf/wagtail-modeltranslation.git#egg=wagtail_modeltranslation`

Tested with Python 3.5 and Django 1.10

**Comment by kevtuck** [comment]
I still have this issue

`from wagtail.wagtailadmin.views.pages import get_page_edit_handler,\ ImportError: cannot import name 'get_page_edit_handler'`

Python 3.4.3
Django 1.10.5
Wagtail 1.8.1

**Comment by Alexandre27** [comment]
Fixed in version 0.6. As django-modeltranslation is now used as a dependency and it has a very quick support for new django versions, in the future it should be easier to fix django incompatibilities. Reopen if any of the problems keeps after upgrading for 0.6
